# -*- coding: utf-8 -*-
"""s0b0s0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SyKR3rBHiyPVfNkoBib68N375BFQycQm
"""

inp = str(input("enter your name without space: "))
#output = s0b0s0

ln=len(inp)
ls=[]
for i in inp: 
  ls.append(i)

print("Full name convert to list",ls)
################
cn=[]
for i in ls[1::2]:
  cn.append(i)
print("Removing elements",cn)

ls=' '.join(ls)
#ls

ls=ls.replace(" ","")
#ls

for x in cn:
    ls=ls.replace(x,"0")

print("Output:",ls)