# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UiU5AbaOGFFBT_9Qzvfi-92uLnnmQ6hG

***Weather Forecasting using LSTM (Long-Short-Term-Memory)***
"""

#Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tfs

print("Hello -this coding is comming soon")
